language: python
python:
- '3.6'
- '3.7'
dist: xenial
install:
- pip install pipenv
- pipenv install --dev
script:
- pylint **/*.py
- python -m pytest --cov=marian
- python ./docs.py
after_success:
- codecov
deploy:
- provider: pypi
  skip_cleanup: true
  on:
    tags: true
    # only release on a single python version.
    python: '3.6'
  edge: true
  user: "__token__"
  password:
    secure: "S2LaSqoiNPKzovVocujiggSv41swVJc2qLNKpXLMRoiKUFIiLmKhOUG4LUGfuGI2e38WA+fLpUf/bNKaA8d8ZhRg31a6NDnA1hS7lPe7nZdY78fTRTlbivIgsf14ECsqwbyJ4mJdGzGcb5EONZlHP2oFsijnyfqq3hsaLQpcheXNTtQITu6GhPrNYYdORzdfEeYZRiHZGSoMgKnmeB/1hhAGS70QeOn2sFkqrScLztsjS6mKoZkmmeXAlDwMJA4g6qN31gkk5m9RSjHOxLT9jGS9X2bDb6xS7fvuqH+xrpPQV8s3y9ExNgy8x3jjAkAowXkXa5Wk3btmSPamZxssqO34/rvyX7psenLH2HU4ImubVCj1QGNuxUrSC6fp+XFYdh8uA3JuFuFO6Z3aVNmNyG5VdX/YCnDBQ4hvWtL2nxeZjTvO/EMqc39F/9eNO5+CkS+ejPnoqYLen8ao7ulWjqtiP43XByWis0OC4Em6E0Rj6dxRfrZjyLhD4brx0zv0igkt4o16n0H61PhCshzCxP97USlxpilksTpvddCYDVldB2qTLalHgYPCNhtQQgyF0EZIE2XPttcjld1ZNqoLIMCP9w0kxiEfIQlpvg1QZRVLJTx2fy3mclMEMEp533cB9ItOiD5CgEYotC8wXekT7uB/Mh5r7xaQKIGI3PJvl90="
- provider: pages
  skip_cleanup: true
  local-dir: "./docs"
  github_token:
    secure: GBIdpeqC/I3ecPYYQK0yZy8ZQrCwuymNqj/1qVUYAqleSGEV/G6ZjHQvg3E6dMdg92aL2dw1vf7xAMM+KORFzBKy1v1/Gr2wUXVNeZzNSzaTEJyfKLBy+gVYDW6J2qQBPO4oP4ARjtuuk3Qgcdu4xkKgl8Iv/9ZhEg3La4koCrHmHHUAA4eO60TBb1cHfs7eTOmQ073ULD9stPmkwEcmYypL3xKEY2MW3MiNfQbfBaGY91hddhbzvnd0ccnanuhlN84qPG/AR3ZkO5Sjfrh4BVhhQpJQG+gE0vJQyi9PsulbzDa9PIs6oHzyOO7aYGiP8efWiSd+QVFrKNa3Z8ZRzCu/AGcejF33zF0W/hAIj7CUp9DJuO8/Vis17s2opVCfvexeyE741e3/0plEMalQ5cInbYAj7vZTq6YIpaoDgSce0st5Z0SX3UBNM/F1gvU5gQg0Um6vmur1qO33xhCMZ1VtROwuOUg/E0mwwax7MPUN0MOkpJYbDKHr6J1DauC7WIAMQfNUPJkOK/vskuLljXdPUDvlI48xaGteyQ5PFpHOXleYTGl87HiJXBs8FpByTUXUDp01dPHMv72GHc6HWQ0j+8/PpC3sAdY0PZfGexzBrB8Hzn+O/Z0hjNqRgezgKV0Lk+/mL9xuqP6acCnhEUBsQDgbXSIJB8FE4PkW5OE=
  keep_history: true
  on:
    branch: master
    tags: true
    python: '3.6'
