language: python
python:
- '3.6'
- '3.7'
dist: xenial
install:
- pip install pipenv
- pipenv install --dev
script:
- pylint **/*.py
- python -m pytest --cov=marian
- python ./docs.py
after_success:
- codecov
deploy:
- provider: pypi
  skip_cleanup: true
  on:
    tags: true
    # only release on a single python version.
    python: '3.6'
  edge: true
  user: "__token__"
  password:
    secure: "S2LaSqoiNPKzovVocujiggSv41swVJc2qLNKpXLMRoiKUFIiLmKhOUG4LUGfuGI2e38WA+fLpUf/bNKaA8d8ZhRg31a6NDnA1hS7lPe7nZdY78fTRTlbivIgsf14ECsqwbyJ4mJdGzGcb5EONZlHP2oFsijnyfqq3hsaLQpcheXNTtQITu6GhPrNYYdORzdfEeYZRiHZGSoMgKnmeB/1hhAGS70QeOn2sFkqrScLztsjS6mKoZkmmeXAlDwMJA4g6qN31gkk5m9RSjHOxLT9jGS9X2bDb6xS7fvuqH+xrpPQV8s3y9ExNgy8x3jjAkAowXkXa5Wk3btmSPamZxssqO34/rvyX7psenLH2HU4ImubVCj1QGNuxUrSC6fp+XFYdh8uA3JuFuFO6Z3aVNmNyG5VdX/YCnDBQ4hvWtL2nxeZjTvO/EMqc39F/9eNO5+CkS+ejPnoqYLen8ao7ulWjqtiP43XByWis0OC4Em6E0Rj6dxRfrZjyLhD4brx0zv0igkt4o16n0H61PhCshzCxP97USlxpilksTpvddCYDVldB2qTLalHgYPCNhtQQgyF0EZIE2XPttcjld1ZNqoLIMCP9w0kxiEfIQlpvg1QZRVLJTx2fy3mclMEMEp533cB9ItOiD5CgEYotC8wXekT7uB/Mh5r7xaQKIGI3PJvl90="
- provider: pages
  skip_cleanup: true
  local-dir: "./docs"
  keep_history: true
  on:
    branch: master
    tags: true
    python: '3.6'
  github_token:
    secure: "Rt+RLcA4CBr8YtVUzWdIJMNffeyIMj/l3ZkUCzwUWrgHq58j6XvTuy8hAv/SlxnYbxu6t/Q9duAQuBEKZ1f8gBoiio29tSndlwgXmkr4FRRVMPDovSF4mEbGfSSvnlS2pzgDHqCfMsCzlr9clNzTZ/4fNQkav0Cf2a8CWnetWdEsLn7Ciu3bqy5F2BF9esB/EJhK4WSvrXUMq/kFLdsdQ6ZD2h5n06OYtofthIa7rj66r2J0VpB2e/t2t/IeGsDqP48D7cXjOEvCXxZwTKGy9mdbPzmtgSDKUfJGXz/geE99/hRH89D5u8YXDSqgB8UZcxxsUYWRzQcgzJV0rNkto1KWF/lHjEeTBVYJxeZVHiENQFseFWi6wmmdJ1ZOZMd3/epPrScT//KfA6HutB5SCdDsKQNtwW0dhdiO5y3CHMoR/OOfVMDQu0RpPmt5A/vI5DQrbSSfeTlxGXRiTGwVTRj48+qpXHnL3n9YNKPckF+SyRsszF1q0NKfVSAhoRw7SPS6ZyK2unSx5GR/JG8vEXgOs6cRLeLI+JG4YcuvdTk3TQ0usU20flmHmgavQjMl5Kj6Ar2Gz3RWhGQKPZqpgp7laixuG3T4Ubo+AQs4qxDueZXg98EVxC9bDnwYmNpGlyuZf3m76CU6SaEDe78G85vDwdINObS2ESs4AUjAewg="
