language: python
python:
- '3.6'
install:
- pip install pipenv
- pipenv install --dev
script:
- pylint **/*.py
- python -m pytest --cov=marian tests
- python ./docs.py
after_success:
- codecov
deploy:
  provider: pypi
  user: digitalvapor
  password:
    secure: IWZ0u8M4WNNDHoN4IgfvfMtuUCx/pGW1XIx8GHPhPfJHhGrOuu+KaWLXoGgVoHVylTy5CPXNXQ/k/uq/x9TxDlKlMQMRxRntwNVldj4v12B2LZcJeWKOyYd4qxy7lZ+TRDUEMmD7a6BZq7kTO6y4wrWg/u1F3e6WyeseATpRDQFsCfJS7ZV1nlMIUHDyEh7dtvAdliKvIKOBBfqcLf6Zub1aEafYQl5/Cc/NoGKNK0YE/fn2v+tbR9TVAJELyvLUYXzQGfSjgMAWFkKgygTIj6524xq7TKRXGoFUUP/+GgnIGaXQ7AjQtGicV5fzm7Tk8CRa60O648FLqn4e6S7SkGk8SFu1VtfCjXIxwKjeso+hT1NO1WlPtYpo1CMT/S7O15KUzRkRoodJG+RivHw2ssoIh0NuTsTJl3lxFVSSbQa+CX6hCjyYO+l5IFaYBdYLD8FrOTHQebkrj2kwYj9rypu8O4VwlH9SSP8mz1jPaUJtZQg3kDSjHSZVtzfHdwXhgbTfQIhZUari7WdhIh4NWuHgbdLcZS5eCgMfLRJdrK1pcxEX0esJqZawcEuO0qC0KxYR8UVs3aD+fKgElJbv5GK7ShUpdzkrEmv5YYLkW2yJ8MiD/ni6ZF/Nio7Mrj/D1zJVvwZK0NXf6Z6nTa7DsZTi2ScmwF6w5pPSuH/xy08=
  on:
    tags: true
